// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY;

// Supabase URL ve anonKey'in doğru şekilde tanımlandığını kontrol et
if (!supabaseUrl || !supabaseAnonKey) {
  console.error('Supabase çevre değişkenleri bulunamadı. Lütfen .env dosyanızı kontrol edin.');
  console.error('VITE_SUPABASE_URL ve VITE_SUPABASE_ANON_KEY tanımlanmalıdır.');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseAnonKey);

// Bağlantı durumunu kontrol et
supabase.auth.onAuthStateChange((event, session) => {
  console.log('Supabase auth event:', event);
  if (event === 'SIGNED_OUT') {
    console.log('Kullanıcı çıkış yaptı');
  } else if (event === 'SIGNED_IN') {
    console.log('Kullanıcı giriş yaptı:', session?.user?.email);
  }
});

// Bağlantı sağlığı kontrolü yapmak için basit bir fonksiyon
export const checkSupabaseConnection = async () => {
  try {
    const { data, error } = await supabase.from('profiles').select('count', { count: 'exact', head: true });
    
    if (error) {
      console.error('Supabase bağlantı hatası:', error.message);
      return { ok: false, error: error.message };
    }
    
    return { ok: true, data };
  } catch (err) {
    console.error('Supabase bağlantısı sırasında beklenmeyen hata:', err);
    return { ok: false, error: err instanceof Error ? err.message : 'Bilinmeyen hata' };
  }
};