// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kolqnwtkwxjgfkcnzzis.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtvbHFud3Rrd3hqZ2ZrY256emlzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk4MzcyNjUsImV4cCI6MjA1NTQxMzI2NX0.ekJ0gJym21sCd-59e33Y46UXoXiOqwExdh9E6_Naw3I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);